import Head from 'next/head'
import {Inter} from '@next/font/google'
import {useWebcam} from "@/hooks/useWebcam";
import {useEffect} from "react";
import {useMediaRecorder} from "@/hooks/useMediaRecorder";


const inter = Inter({subsets: ['latin']})

export default function Home() {


    const mediaStream: MediaStream | undefined = useWebcam()
    const {startRecording, stopRecording, savedRecordingUrl, isRecording} = useMediaRecorder(mediaStream)


    console.log("savedRecordingUrl",savedRecordingUrl)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <video></video>
                <button className="bg-red-500 text-white px-4 py-2" onClick={isRecording ? stopRecording : startRecording}>{`${isRecording ? "Stop" : "Start"} Recording`}</button>
                {savedRecordingUrl ? (<div>
                    <h1>Playback</h1>
                    <video id={"playback"} src={savedRecordingUrl} controls></video>
                </div>) : null}
            </main>
        </>
    )
}
